'use strict';
exports.webpack = require('webpack');
exports.merge = require('webpack-merge');
exports.build = require('./tool/build');
exports.Utils = require('./utils/utils');
exports.Loader = require('./utils/loader');
exports.WebpackBaseBuilder = require('./lib/base');
exports.WebpackClientBuilder = require('./lib/client');
exports.WebpackServerBuilder = require('./lib/server');
exports.getConfig = config => require('./lib/config')(config);
